# Generated by Django 4.0.4 on 2023-01-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30, verbose_name='User Name')),
                ('mail_address', models.EmailField(max_length=40, verbose_name='Email Address')),
                ('messages', models.TextField(max_length=120, verbose_name='Messages')),
            ],
        ),
    ]
