# Generated by Django 4.0.4 on 2022-10-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_menu_options_menu_price_alter_menu_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Drink Menu',
            },
        ),
        migrations.CreateModel(
            name='SetMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Set Menu',
            },
        ),
        migrations.RenameModel(
            old_name='Menu',
            new_name='BurgerMenu',
        ),
        migrations.AlterModelOptions(
            name='burgermenu',
            options={'verbose_name_plural': 'Burger Menu'},
        ),
    ]
