# Generated by Django 4.0.5 on 2022-10-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_drinkmenu_setmenu_rename_menu_burgermenu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burgermenu',
            name='price',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='drinkmenu',
            name='price',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='setmenu',
            name='price',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
