# Generated by Django 4.0.4 on 2022-10-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='img/default.jpg', upload_to='profile_pics'),
        ),
    ]
