# Generated by Django 4.0.4 on 2022-12-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_post_remove_useravatar_userimage_delete_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=120, null=True),
        ),
    ]
